spring.application.name=catalogo

# Hibernate: 'update' mantém os dados e adiciona novos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 (localhost:8080/h2-console)
# JDBC URL no navegador deve ser: jdbc:h2:file:~/catalogodb
spring.h2.console.enabled=true

# Inicialização do SQL (import.sql)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always